import { z } from 'zod';
import { connectToDatabase } from '@/lib/db/connect';
import Conversation from '@/models/Conversation';
import Message from '@/models/Message';

const schema = z.object({ selectedModel: z.string().max(80).optional(), assistantMode: z.string().max(80).optional() });
const map = (conversation: { _id: unknown; title: string; selectedModel: string; assistantMode: string; createdAt: Date; updatedAt: Date; isPinned?: boolean; isArchived?: boolean; activeEntityId?: string | null; activeEntityName?: string | null; activeEntityType?: string | null }) => ({ id: String(conversation._id), title: conversation.title, model: conversation.selectedModel, assistantMode: conversation.assistantMode, createdAt: conversation.createdAt.toISOString(), updatedAt: conversation.updatedAt.toISOString(), isPinned: conversation.isPinned === true, isArchived: conversation.isArchived === true, activeEntityId: conversation.activeEntityId ?? null, activeEntityName: conversation.activeEntityName ?? null, activeEntityType: conversation.activeEntityType ?? null, messages: [] });

export async function GET() { try { await connectToDatabase(); const conversations = await Conversation.find().sort({ isPinned: -1, updatedAt: -1 }).lean(); const activeConversationIds = await Message.distinct('conversationId'); const activeIds = new Set(activeConversationIds.map(String)); return Response.json({ conversations: conversations.filter((conversation) => activeIds.has(String(conversation._id))).map(map) }); } catch (error) { console.error('[conversations] list', error); return Response.json({ error: 'Database unavailable.' }, { status: 503 }); } }
export async function POST(request: Request) { const body = await request.json().catch(() => null); const parsed = schema.safeParse(body ?? {}); if (!parsed.success) return Response.json({ error: 'Invalid conversation settings.' }, { status: 400 }); try { await connectToDatabase(); const conversation = await Conversation.create({ selectedModel: parsed.data.selectedModel ?? 'jarvis-v4', assistantMode: parsed.data.assistantMode ?? 'general' }); return Response.json({ conversation: map(conversation) }, { status: 201 }); } catch (error) { console.error('[conversations] create', error); return Response.json({ error: 'Database unavailable.' }, { status: 503 }); } }
