import mongoose from 'mongoose';
import KnowledgeChunk from '@/models/KnowledgeChunk';
import KnowledgeDocument from '@/models/KnowledgeDocument';
import { connectToDatabase } from '@/lib/db/connect';

export const runtime = 'nodejs';
const valid = (id: string) => mongoose.isObjectIdOrHexString(id);
export async function GET(_: Request, { params }: { params: Promise<{ documentId: string }> }) { const { documentId } = await params; if (!valid(documentId)) return Response.json({ error: 'Invalid document ID.' }, { status: 400 }); try { await connectToDatabase(); const [document, chunks] = await Promise.all([KnowledgeDocument.findById(documentId).select('-originalContent').lean(), KnowledgeChunk.find({ documentId }).sort({ chunkIndex: 1 }).select('-embedding').lean()]); if (!document) return Response.json({ error: 'Knowledge document not found.' }, { status: 404 }); return Response.json({ document: { id: String(document._id), title: document.title, description: document.description, status: document.status, chunkCount: document.chunkCount, visibility: document.visibility, createdAt: document.createdAt.toISOString(), updatedAt: document.updatedAt.toISOString() }, chunks: chunks.map((chunk) => ({ id: String(chunk._id), chunkIndex: chunk.chunkIndex, content: chunk.content, tokenEstimate: chunk.tokenEstimate, documentTitle: chunk.metadata?.documentTitle ?? document.title })) }); } catch { return Response.json({ error: 'Knowledge document is unavailable.' }, { status: 503 }); } }
export async function DELETE(_: Request, { params }: { params: Promise<{ documentId: string }> }) { const { documentId } = await params; if (!valid(documentId)) return Response.json({ error: 'Invalid document ID.' }, { status: 400 }); try { await connectToDatabase(); const document = await KnowledgeDocument.findByIdAndDelete(documentId); if (!document) return Response.json({ error: 'Knowledge document not found.' }, { status: 404 }); await KnowledgeChunk.deleteMany({ documentId }); return Response.json({ success: true }); } catch { return Response.json({ error: 'Unable to delete knowledge document.' }, { status: 503 }); } }
