import { z } from 'zod';
import KnowledgeDocument from '@/models/KnowledgeDocument';
import { ingestDocument, RAG_CONFIG } from '@/lib/ai/rag';
import { connectToDatabase } from '@/lib/db/connect';

export const runtime = 'nodejs';
const schema = z.object({ title: z.string().trim().min(1).max(RAG_CONFIG.maxTitleCharacters), content: z.string().trim().min(1).max(RAG_CONFIG.maxDocumentCharacters), description: z.string().trim().max(500).optional(), visibility: z.enum(['private', 'public']).default('private') });
const serialize = (document: { _id: unknown; title: string; description?: string | null; sourceType: string; status: string; chunkCount: number; embeddingModel: string; errorMessage?: string | null; visibility: string; createdAt: Date; updatedAt: Date }) => ({ id: String(document._id), title: document.title, description: document.description ?? undefined, sourceType: document.sourceType, status: document.status, chunkCount: document.chunkCount, embeddingModel: document.embeddingModel, errorMessage: document.errorMessage ?? undefined, visibility: document.visibility, createdAt: document.createdAt.toISOString(), updatedAt: document.updatedAt.toISOString() });
export async function GET() { try { await connectToDatabase(); const documents = await KnowledgeDocument.find().sort({ createdAt: -1 }).select('-originalContent').lean(); return Response.json({ documents: documents.map(serialize) }, { headers: { 'Cache-Control': 'no-store' } }); } catch (error) { console.error('[Knowledge] List failed:', error); return Response.json({ error: 'Knowledge base is unavailable.' }, { status: 503 }); } }
export async function POST(request: Request) { let body: unknown; try { body = await request.json(); } catch { return Response.json({ error: 'Invalid JSON request body.' }, { status: 400 }); } const parsed = schema.safeParse(body); if (!parsed.success) return Response.json({ error: 'Provide a valid title, content, and visibility.' }, { status: 400 }); try { const document = await ingestDocument(parsed.data); return Response.json({ document: serialize(document) }, { status: 201 }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : 'Knowledge processing failed.' }, { status: 502 }); } }
