'use client';
import React, { createContext, useContext, useEffect, useMemo, useRef, useState } from 'react';
import type { AssistantMode } from '@/lib/ai/prompts';
import { formatTimestamp, generateId } from '@/lib/utils';
import type { AIModelId, Conversation, Message, PersonaMode, UserSettings } from '@/types/chat';

const DEFAULT_MODEL: AIModelId = 'jarvis-v4'; const DEFAULT_MODE: AssistantMode = 'general'; const MAX_HISTORY = 30;
type Context = { chats: Conversation[]; activeChatId: string | null; activeChat: Conversation | null; searchQuery: string; setSearchQuery: (v: string) => void; activeModelId: AIModelId; setActiveModelId: (v: AIModelId) => void; assistantMode: AssistantMode; setAssistantMode: (v: AssistantMode) => void; persona: PersonaMode; setPersona: (v: PersonaMode) => void; isStreaming: boolean; isSidebarOpen: boolean; setIsSidebarOpen: (v: boolean) => void; toggleSidebar: () => void; isSettingsOpen: boolean; setIsSettingsOpen: (v: boolean) => void; settings: UserSettings; updateSettings: (v: Partial<UserSettings>) => void; createNewChat: () => Promise<void>; selectChat: (id: string) => Promise<void>; sendMessage: (content: string) => Promise<void>; stopGenerating: () => void; regenerateMessage: (id: string) => Promise<void>; editPromptAndSend: (id: string, content: string) => Promise<void>; deleteChat: (id: string) => Promise<void>; renameChat: (id: string, title: string) => Promise<void>; togglePinChat: (id: string) => Promise<void>; toggleMessageLike: (id: string, s: 'liked' | 'disliked') => void; clearAllChats: () => void; exportChatHistory: (f: 'json' | 'markdown') => void; };
const ChatContext = createContext<Context | undefined>(undefined);
const titleFor = (text: string) => { const words = text.replace(/\s+/g, ' ').trim().split(' ').slice(0, 8).join(' '); return words.length > 50 ? `${words.slice(0, 47)}…` : words; };
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const payload = await response.json().catch(() => null) as T & { error?: string }; if (!response.ok) throw new Error(payload?.error || 'Database request failed.'); return payload; }

export function ChatProvider({ children }: { children: React.ReactNode }) {
 const [chats, setChats] = useState<Conversation[]>([]); const [activeChatId, setActiveChatId] = useState<string | null>(null); const [searchQuery, setSearchQuery] = useState(''); const [persona, setPersona] = useState<PersonaMode>('jarvis'); const [isStreaming, setIsStreaming] = useState(false); const [isSidebarOpen, setIsSidebarOpen] = useState(true); const [isSettingsOpen, setIsSettingsOpen] = useState(false); const [settings, setSettings] = useState<UserSettings>({ theme:'dark', defaultModel:DEFAULT_MODEL, persona:'jarvis', systemPrompt:'', soundEffects:true, streamSpeed:25, sendOnEnter:true, temperature:.7 }); const abortRef = useRef<AbortController | null>(null);
 const activeChat = useMemo(() => chats.find((chat) => chat.id === activeChatId) ?? null, [chats, activeChatId]);
 const replaceChat = (conversation: Conversation) => setChats((current) => [conversation, ...current.filter((chat) => chat.id !== conversation.id)]);
 useEffect(() => { void api<{ conversations: Conversation[] }>('/api/conversations').then(async ({ conversations }) => { setChats(conversations); if (conversations[0]) { const { conversation } = await api<{ conversation: Conversation }>(`/api/conversations/${conversations[0].id}`); setChats((current) => [conversation, ...current.filter((chat) => chat.id !== conversation.id)]); setActiveChatId(conversation.id); } }).catch((error) => console.error('Unable to load conversations.', error)); }, []);
 const selectChat = async (id: string) => { if (isStreaming) return; const { conversation } = await api<{ conversation: Conversation }>(`/api/conversations/${id}`); replaceChat(conversation); setActiveChatId(id); };
 const createNewChat = async () => { if (isStreaming) return; const { conversation } = await api<{ conversation: Conversation }>('/api/conversations', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ model:DEFAULT_MODEL, assistantMode:DEFAULT_MODE }) }); replaceChat(conversation); setActiveChatId(conversation.id); };
 const patch = async (id: string, body: Record<string, unknown>) => { const { conversation } = await api<{ conversation: Conversation }>(`/api/conversations/${id}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) }); const current = chats.find((chat) => chat.id === id); replaceChat({ ...conversation, messages: current?.messages ?? [] }); };
 const setActiveModelId = (model: AIModelId) => { if (activeChat) void patch(activeChat.id, { model }); }; const setAssistantMode = (assistantMode: AssistantMode) => { if (activeChat) void patch(activeChat.id, { assistantMode }); };
 const persistMessage = (conversationId: string, role: 'user'|'assistant', content: string) => api(`/api/conversations/${conversationId}/messages`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({role,content}) });
 const stream = async (conversation: Conversation, assistantId: string, history: Message[]) => { const controller = new AbortController(); abortRef.current = controller; setIsStreaming(true); let content=''; try { const response = await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history.slice(-MAX_HISTORY).map(({role,content})=>({role,content})),mode:conversation.assistantMode}),signal:controller.signal}); if(!response.ok) throw new Error(((await response.json().catch(()=>null)) as {error?:string}|null)?.error || 'AI request failed.'); if(!response.body) throw new Error('No stream body received.'); const reader=response.body.getReader(), decoder=new TextDecoder(); while(true){const {done,value}=await reader.read();if(done)break;content+=decoder.decode(value,{stream:true});const next=content;setChats(current=>current.map(chat=>chat.id===conversation.id?{...chat,updatedAt:new Date().toISOString(),messages:chat.messages.map(message=>message.id===assistantId?{...message,content:next,status:'streaming'}:message)}:chat));} await persistMessage(conversation.id,'assistant',content); setChats(current=>current.map(chat=>chat.id===conversation.id?{...chat,messages:chat.messages.map(message=>message.id===assistantId?{...message,status:'complete'}:message)}:chat)); } catch(error){if(error instanceof DOMException&&error.name==='AbortError')return;const message=error instanceof Error?error.message:'AI request failed.';setChats(current=>current.map(chat=>chat.id===conversation.id?{...chat,messages:chat.messages.map(item=>item.id===assistantId?{...item,content:`⚠️ **AI Service Notice**: ${message}`,status:'error',error:{message,retryable:true}}:item)}:chat));} finally { if(abortRef.current===controller){abortRef.current=null;setIsStreaming(false);} } };
 const sendMessage = async (raw: string) => { const content=raw.trim(); if(!content||isStreaming)return; if(!activeChat){await createNewChat(); return;} let conversation:Conversation=activeChat; const now=new Date().toISOString(); const user:Message={id:`msg-${generateId()}`,role:'user',content,createdAt:now,status:'submitted'}; const assistant:Message={id:`msg-${generateId()}`,role:'assistant',content:'',createdAt:now,status:'streaming',model:conversation.model}; const first=conversation.messages.length===0; setChats(current=>current.map(chat=>chat.id===conversation.id?{...chat,title:first?titleFor(content):chat.title,updatedAt:now,messages:[...chat.messages,user,assistant]}:chat)); try { await persistMessage(conversation.id,'user',content); if(first) await patch(conversation.id,{title:titleFor(content)}); conversation={...conversation,title:first?titleFor(content):conversation.title,messages:[...conversation.messages,user]}; void stream(conversation,assistant.id,[...conversation.messages,user]); } catch(error){const message=error instanceof Error?error.message:'Unable to save message.';setChats(current=>current.map(chat=>chat.id===conversation.id?{...chat,messages:chat.messages.map(item=>item.id===assistant.id?{...item,content:`⚠️ ${message}`,status:'error',error:{message,retryable:true}}:item)}:chat));} };
 const stopGenerating=()=>abortRef.current?.abort(); const regenerateMessage=async(id:string)=>{if(!activeChat||isStreaming)return;const index=activeChat.messages.findIndex(m=>m.id===id);if(index<0)return;setChats(current=>current.map(chat=>chat.id===activeChat.id?{...chat,messages:chat.messages.map(m=>m.id===id?{...m,content:'',status:'streaming',error:undefined}:m)}:chat));void stream(activeChat,id,activeChat.messages.slice(0,index));}; const editPromptAndSend=async()=>{};
 const deleteChat=async(id:string)=>{if(isStreaming)return;await api(`/api/conversations/${id}`,{method:'DELETE'});const remaining=chats.filter(chat=>chat.id!==id);setChats(remaining);if(activeChatId===id){if(remaining[0])await selectChat(remaining[0].id);else setActiveChatId(null);}}; const renameChat=async(id:string,title:string)=>{if(title.trim())await patch(id,{title:title.trim()});}; const togglePinChat=async(id:string)=>{const chat=chats.find(item=>item.id===id);if(chat)await patch(id,{isPinned:!chat.isPinned});};
 const toggleMessageLike=(id:string,s:'liked'|'disliked')=>setChats(current=>current.map(chat=>chat.id===activeChatId?{...chat,messages:chat.messages.map(message=>message.id===id?{...message,likeStatus:message.likeStatus===s?null:s}:message)}:chat)); const clearAllChats=()=>{}; const exportChatHistory=(format:'json'|'markdown')=>{if(!activeChat)return;const data=format==='json'?JSON.stringify(activeChat,null,2):`# ${activeChat.title}\n\n${activeChat.messages.map(m=>`### ${m.role} (${formatTimestamp(m.createdAt)})\n${m.content}`).join('\n\n')}`;const a=document.createElement('a');a.href=`data:text/${format};charset=utf-8,${encodeURIComponent(data)}`;a.download=`jarvis_${activeChat.id}.${format==='json'?'json':'md'}`;a.click();};
 return <ChatContext.Provider value={{chats,activeChatId,activeChat,searchQuery,setSearchQuery,activeModelId:activeChat?.model??DEFAULT_MODEL,setActiveModelId,assistantMode:activeChat?.assistantMode??DEFAULT_MODE,setAssistantMode,persona,setPersona,isStreaming,isSidebarOpen,setIsSidebarOpen,toggleSidebar:()=>setIsSidebarOpen(v=>!v),isSettingsOpen,setIsSettingsOpen,settings,updateSettings:v=>setSettings(s=>({...s,...v})),createNewChat,selectChat,sendMessage,stopGenerating,regenerateMessage,editPromptAndSend,deleteChat,renameChat,togglePinChat,toggleMessageLike,clearAllChats,exportChatHistory}}>{children}</ChatContext.Provider>;
}
export function useChat(){const context=useContext(ChatContext);if(!context)throw new Error('useChat must be used within ChatProvider.');return context;}
