'use client';

import React, { createContext, useContext, useEffect, useMemo, useRef, useState } from 'react';
import type { AssistantMode } from '@/lib/ai/prompts';
import { formatTimestamp, generateId } from '@/lib/utils';
import type { AIModelId, Conversation, Message, PersonaMode, UserSettings } from '@/types/chat';

const DEFAULT_MODEL: AIModelId = 'jarvis-v4';
const DEFAULT_MODE: AssistantMode = 'general';
const MAX_HISTORY = 30;
type KnowledgeMode = 'off' | 'public' | 'private';
type Context = {
  chats: Conversation[]; activeChatId: string | null; activeChat: Conversation | null; searchQuery: string; setSearchQuery: (value: string) => void;
  activeModelId: AIModelId; setActiveModelId: (value: AIModelId) => void; assistantMode: AssistantMode; setAssistantMode: (value: AssistantMode) => void;
  knowledgeMode: KnowledgeMode; setKnowledgeMode: (value: KnowledgeMode) => void; persona: PersonaMode; setPersona: (value: PersonaMode) => void;
  isStreaming: boolean; isSidebarOpen: boolean; setIsSidebarOpen: (value: boolean) => void; toggleSidebar: () => void; isSettingsOpen: boolean; setIsSettingsOpen: (value: boolean) => void;
  settings: UserSettings; updateSettings: (value: Partial<UserSettings>) => void; createNewChat: () => Promise<Conversation | null>; selectChat: (id: string) => Promise<void>; sendMessage: (content: string) => Promise<void>; stopGenerating: () => void;
  regenerateMessage: (id: string) => Promise<void>; editPromptAndSend: (id: string, content: string) => Promise<void>; deleteChat: (id: string) => Promise<void>; renameChat: (id: string, title: string) => Promise<void>; togglePinChat: (id: string) => Promise<void>;
  toggleMessageLike: (id: string, state: 'liked' | 'disliked') => void; clearAllChats: () => void; exportChatHistory: (format: 'json' | 'markdown') => void;
};
const ChatContext = createContext<Context | undefined>(undefined);
const titleFor = (text: string) => { const title = text.replace(/\s+/g, ' ').trim().split(' ').slice(0, 8).join(' '); return title.length > 50 ? `${title.slice(0, 47)}…` : title; };
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const data = await response.json().catch(() => null) as T & { error?: string }; if (!response.ok) throw new Error(data?.error || 'Database request failed.'); return data; }

export function ChatProvider({ children }: { children: React.ReactNode }) {
  const [chats, setChats] = useState<Conversation[]>([]); const [activeChatId, setActiveChatId] = useState<string | null>(null); const [searchQuery, setSearchQuery] = useState(''); const [knowledgeMode, setKnowledgeMode] = useState<KnowledgeMode>('public');
  const [persona, setPersona] = useState<PersonaMode>('jarvis'); const [isStreaming, setIsStreaming] = useState(false); const [isSidebarOpen, setIsSidebarOpen] = useState(true); const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [settings, setSettings] = useState<UserSettings>({ theme: 'dark', defaultModel: DEFAULT_MODEL, persona: 'jarvis', systemPrompt: '', soundEffects: true, streamSpeed: 25, sendOnEnter: true, temperature: .7 });
  const abortRef = useRef<AbortController | null>(null);
  const activeChat = useMemo(() => chats.find((chat) => chat.id === activeChatId) ?? null, [chats, activeChatId]);
  const replaceChat = (conversation: Conversation) => setChats((current) => [conversation, ...current.filter((chat) => chat.id !== conversation.id)]);
  useEffect(() => { void api<{ conversations: Conversation[] }>('/api/conversations').then(async ({ conversations }) => { setChats(conversations); if (conversations[0]) { const { conversation } = await api<{ conversation: Conversation }>(`/api/conversations/${conversations[0].id}`); replaceChat(conversation); setActiveChatId(conversation.id); } }).catch((error) => console.error('Unable to load conversations.', error)); }, []);
  const selectChat = async (id: string) => { if (isStreaming || !id) return; const { conversation } = await api<{ conversation: Conversation }>(`/api/conversations/${id}`); replaceChat(conversation); setActiveChatId(id); };
  const createNewChat = async (): Promise<Conversation | null> => { if (isStreaming) return null; if (activeChat?.title === 'New Chat' && !activeChat.messages.length) return activeChat; const { conversation } = await api<{ conversation: Conversation }>('/api/conversations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ selectedModel: DEFAULT_MODEL, assistantMode: DEFAULT_MODE }) }); replaceChat(conversation); setActiveChatId(conversation.id); return conversation; };
  const patch = async (id: string, body: Record<string, unknown>) => { const { conversation } = await api<{ conversation: Conversation }>(`/api/conversations/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); setChats((current) => { const existing = current.find((chat) => chat.id === id); return [{ ...conversation, messages: existing?.messages ?? [] }, ...current.filter((chat) => chat.id !== id)]; }); };
  const persistMessage = (conversationId: string, role: 'user' | 'assistant', content: string, traceId?: string) => api(`/api/conversations/${conversationId}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ role, content, traceId }) });
  const stream = async (conversation: Conversation, assistantId: string, history: Message[]) => {
    const controller = new AbortController(); abortRef.current = controller; setIsStreaming(true); let content = '';
    try {
      const chatMode = knowledgeMode === 'off' ? 'normal' : 'knowledge_hybrid';
      const chatPayload = { messages: history.slice(-MAX_HISTORY).map(({ role, content: messageContent }) => ({ role, content: messageContent })), mode: conversation.assistantMode, knowledgeMode, chatMode };
      if (process.env.NODE_ENV !== 'production') console.info('[Chat] selected knowledgeMode:', knowledgeMode);
      const response = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(chatPayload), signal: controller.signal });
      if (!response.ok) {
        const metadataHeader = response.headers.get('X-Jarvis-Answer-Metadata');
        let traceId: string | undefined;
        try { traceId = metadataHeader ? (JSON.parse(decodeURIComponent(metadataHeader)) as { traceId?: string }).traceId : undefined; } catch { /* Preserve a readable provider error. */ }
        const body = await response.text().catch(() => '');
        const error = new Error(body || 'AI request failed.') as Error & { traceId?: string };
        error.traceId = traceId;
        throw error;
      }
      let sources: Message['sources'] = []; let answerMetadata: Message['answerMetadata']; try { const raw = response.headers.get('X-Jarvis-Knowledge-Sources'); sources = raw ? JSON.parse(decodeURIComponent(raw)) : []; const metadata = response.headers.get('X-Jarvis-Answer-Metadata'); answerMetadata = metadata ? JSON.parse(decodeURIComponent(metadata)) : undefined; } catch { sources = []; answerMetadata = undefined; }
      if (!response.body) throw new Error('No stream body received.'); const reader = response.body.getReader(); const decoder = new TextDecoder();
      while (true) { const { done, value } = await reader.read(); if (done) break; content += decoder.decode(value, { stream: true }); const next = content; setChats((current) => current.map((chat) => chat.id === conversation.id ? { ...chat, updatedAt: new Date().toISOString(), messages: chat.messages.map((message) => message.id === assistantId ? { ...message, content: next, status: 'streaming' } : message) } : chat)); }
      if (!content.trim()) throw new Error('The AI service returned an empty response. Please try again.');
      const traceId = answerMetadata?.traceId; await persistMessage(conversation.id, 'assistant', content, traceId); if (process.env.NODE_ENV !== 'production') console.info('[Chat] assistant message persisted with trace', { assistantId, traceId, traceReturnedToClient: Boolean(traceId) }); setChats((current) => current.map((chat) => chat.id === conversation.id ? { ...chat, messages: chat.messages.map((message) => message.id === assistantId ? { ...message, status: 'complete', sources, answerMetadata, traceId } : message) } : chat));
    } catch (error) { if (error instanceof DOMException && error.name === 'AbortError') return; const message = error instanceof Error ? error.message : 'AI request failed.'; setChats((current) => current.map((chat) => chat.id === conversation.id ? { ...chat, messages: chat.messages.map((item) => item.id === assistantId ? { ...item, content: `⚠️ **AI Service Notice**: ${message}`, status: 'error', error: { message, retryable: true } } : item) } : chat)); }
    finally { if (abortRef.current === controller) { abortRef.current = null; setIsStreaming(false); } }
  };
  const sendMessage = async (raw: string) => { const content = raw.trim(); if (!content || isStreaming) return; const createdOrActive = activeChat ?? await createNewChat(); if (!createdOrActive) return; let conversation: Conversation = createdOrActive; const now = new Date().toISOString(); const user: Message = { id: `msg-${generateId()}`, role: 'user', content, createdAt: now, status: 'submitted' }; const assistant: Message = { id: `msg-${generateId()}`, role: 'assistant', content: '', createdAt: now, status: 'streaming', model: conversation.model }; const first = !conversation.messages.length; setChats((current) => current.map((chat) => chat.id === conversation.id ? { ...chat, title: first ? titleFor(content) : chat.title, updatedAt: now, messages: [...chat.messages, user, assistant] } : chat)); try { await persistMessage(conversation.id, 'user', content); if (first) await patch(conversation.id, { title: titleFor(content) }); conversation = { ...conversation, title: first ? titleFor(content) : conversation.title, messages: [...conversation.messages, user] }; void stream(conversation, assistant.id, conversation.messages); } catch (error) { const message = error instanceof Error ? error.message : 'Unable to save message.'; setChats((current) => current.map((chat) => chat.id === conversation.id ? { ...chat, messages: chat.messages.map((item) => item.id === assistant.id ? { ...item, content: `⚠️ ${message}`, status: 'error', error: { message, retryable: true } } : item) } : chat)); } };
  const regenerateMessage = async (id: string) => { if (!activeChat || isStreaming) return; const index = activeChat.messages.findIndex((message) => message.id === id); if (index < 0) return; setChats((current) => current.map((chat) => chat.id === activeChat.id ? { ...chat, messages: chat.messages.map((message) => message.id === id ? { ...message, content: '', status: 'streaming', error: undefined } : message) } : chat)); void stream(activeChat, id, activeChat.messages.slice(0, index)); };
  const deleteChat = async (id: string) => { if (isStreaming) return; await api(`/api/conversations/${id}`, { method: 'DELETE' }); const remaining = chats.filter((chat) => chat.id !== id); setChats(remaining); if (activeChatId === id) { if (remaining[0]) await selectChat(remaining[0].id); else setActiveChatId(null); } };
  const exportChatHistory = (format: 'json' | 'markdown') => { if (!activeChat) return; const data = format === 'json' ? JSON.stringify(activeChat, null, 2) : `# ${activeChat.title}\n\n${activeChat.messages.map((message) => `### ${message.role} (${formatTimestamp(message.createdAt)})\n${message.content}`).join('\n\n')}`; const anchor = document.createElement('a'); anchor.href = `data:text/${format};charset=utf-8,${encodeURIComponent(data)}`; anchor.download = `jarvis_${activeChat.id}.${format === 'json' ? 'json' : 'md'}`; anchor.click(); };
  return <ChatContext.Provider value={{ chats, activeChatId, activeChat, searchQuery, setSearchQuery, activeModelId: activeChat?.model ?? DEFAULT_MODEL, setActiveModelId: (model) => { if (activeChat) void patch(activeChat.id, { selectedModel: model }); }, assistantMode: activeChat?.assistantMode ?? DEFAULT_MODE, setAssistantMode: (mode) => { if (activeChat) void patch(activeChat.id, { assistantMode: mode }); }, knowledgeMode, setKnowledgeMode, persona, setPersona, isStreaming, isSidebarOpen, setIsSidebarOpen, toggleSidebar: () => setIsSidebarOpen((value) => !value), isSettingsOpen, setIsSettingsOpen, settings, updateSettings: (value) => setSettings((current) => ({ ...current, ...value })), createNewChat, selectChat, sendMessage, stopGenerating: () => abortRef.current?.abort(), regenerateMessage, editPromptAndSend: async () => undefined, deleteChat, renameChat: async (id, title) => { if (title.trim()) await patch(id, { title: title.trim() }); }, togglePinChat: async (id) => { const chat = chats.find((item) => item.id === id); if (chat) await patch(id, { isPinned: !chat.isPinned }); }, toggleMessageLike: (id, state) => setChats((current) => current.map((chat) => chat.id === activeChatId ? { ...chat, messages: chat.messages.map((message) => message.id === id ? { ...message, likeStatus: message.likeStatus === state ? null : state } : message) } : chat)), clearAllChats: () => undefined, exportChatHistory }}>{children}</ChatContext.Provider>;
}
export function useChat() { const context = useContext(ChatContext); if (!context) throw new Error('useChat must be used within ChatProvider.'); return context; }
