import mongoose from 'mongoose';
import { z } from 'zod';
import { connectToDatabase } from '@/lib/db/connect';
import Conversation from '@/models/Conversation';
import Message from '@/models/Message';

const updateSchema = z.object({ title: z.string().trim().min(1).max(50).optional(), selectedModel: z.string().max(80).optional(), assistantMode: z.string().max(80).optional(), isPinned: z.boolean().optional(), isArchived: z.boolean().optional() });
const validId = (id: string) => mongoose.isValidObjectId(id);
const mapConversation = (conversation: { _id: unknown; title: string; selectedModel: string; assistantMode: string; createdAt: Date; updatedAt: Date; isPinned?: boolean; isArchived?: boolean }, messages: unknown[] = []) => ({ id: String(conversation._id), title: conversation.title, model: conversation.selectedModel, assistantMode: conversation.assistantMode, createdAt: conversation.createdAt.toISOString(), updatedAt: conversation.updatedAt.toISOString(), isPinned: conversation.isPinned === true, isArchived: conversation.isArchived === true, messages });

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; if (!validId(id)) return Response.json({ error: 'Invalid conversation ID.' }, { status: 400 }); try { await connectToDatabase(); const [conversation, messages] = await Promise.all([Conversation.findById(id).lean(), Message.find({ conversationId: id }).sort({ createdAt: 1 }).lean()]); if (!conversation) return Response.json({ error: 'Conversation not found.' }, { status: 404 }); const mappedMessages = messages.map((message) => ({ id: String(message._id), role: message.role === 'system' ? 'assistant' : message.role, content: message.content, createdAt: message.createdAt.toISOString(), status: message.status === 'completed' ? 'complete' : message.status })); return Response.json({ conversation: mapConversation(conversation, mappedMessages) }); } catch { return Response.json({ error: 'Database unavailable.' }, { status: 503 }); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; if (!validId(id)) return Response.json({ error: 'Invalid conversation ID.' }, { status: 400 }); const parsed = updateSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return Response.json({ error: 'Invalid conversation update.' }, { status: 400 }); try { await connectToDatabase(); const conversation = await Conversation.findByIdAndUpdate(id, parsed.data, { new: true }).lean(); if (!conversation) return Response.json({ error: 'Conversation not found.' }, { status: 404 }); return Response.json({ conversation: mapConversation(conversation) }); } catch { return Response.json({ error: 'Database unavailable.' }, { status: 503 }); } }
export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; if (!validId(id)) return Response.json({ error: 'Invalid conversation ID.' }, { status: 400 }); try { await connectToDatabase(); const conversation = await Conversation.findByIdAndDelete(id); if (!conversation) return Response.json({ error: 'Conversation not found.' }, { status: 404 }); await Message.deleteMany({ conversationId: id }); return Response.json({ success: true }); } catch { return Response.json({ error: 'Database unavailable.' }, { status: 503 }); } }
