import { z } from 'zod';
import { connectToDatabase } from '@/lib/db/connect';
import Conversation from '@/models/Conversation';
import Message from '@/models/Message';

const updateSchema = z.object({ title: z.string().trim().min(1).max(50).optional(), model: z.string().max(80).optional(), assistantMode: z.string().max(80).optional(), isPinned: z.boolean().optional(), isArchived: z.boolean().optional() });
const mapMessage = (message: { _id: unknown; role: 'user' | 'assistant'; content: string; createdAt: Date }) => ({ id: String(message._id), role: message.role, content: message.content, createdAt: message.createdAt.toISOString(), status: 'complete' as const });
export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; try { await connectToDatabase(); const [conversation, messages] = await Promise.all([Conversation.findById(id).lean(), Message.find({ conversationId: id }).sort({ createdAt: 1 }).lean()]); if (!conversation) return Response.json({ error: 'Conversation not found.' }, { status: 404 }); return Response.json({ conversation: { id: String(conversation._id), title: conversation.title, model: conversation.model, assistantMode: conversation.assistantMode, createdAt: conversation.createdAt.toISOString(), updatedAt: conversation.updatedAt.toISOString(), isPinned: conversation.isPinned === true, isArchived: conversation.isArchived === true, messages: messages.map(mapMessage) } }); } catch { return Response.json({ error: 'Database unavailable.' }, { status: 503 }); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const parsed = updateSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return Response.json({ error: 'Invalid conversation update.' }, { status: 400 }); const { id } = await params; try { await connectToDatabase(); const conversation = await Conversation.findByIdAndUpdate(id, parsed.data, { new: true }).lean(); if (!conversation) return Response.json({ error: 'Conversation not found.' }, { status: 404 }); return Response.json({ conversation }); } catch { return Response.json({ error: 'Database unavailable.' }, { status: 503 }); } }
export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; try { await connectToDatabase(); const conversation = await Conversation.findByIdAndDelete(id); if (!conversation) return Response.json({ error: 'Conversation not found.' }, { status: 404 }); await Message.deleteMany({ conversationId: id }); return new Response(null, { status: 204 }); } catch { return Response.json({ error: 'Database unavailable.' }, { status: 503 }); } }
