'use client';

import { useState } from 'react';
import { LoaderCircle, Search } from 'lucide-react';

type Result = { documentTitle: string; chunkIndex: number; content: string; score: number };
export function RagPlayground() { const [query, setQuery] = useState('What is the refund period?'); const [results, setResults] = useState<Result[]>([]); const [context, setContext] = useState(''); const [answer, setAnswer] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const run = async () => { if (!query.trim() || loading) return; setLoading(true); setError(''); setAnswer(''); try { const searchResponse = await fetch('/api/knowledge/search', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query, visibility: 'public', limit: 5 }) }); const search = await searchResponse.json(); if (!searchResponse.ok) throw new Error(search.error); setResults(search.results); setContext(search.context); const response = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: [{ role: 'user', content: query }], knowledgeMode: 'public', mode: 'general' }) }); if (!response.ok || !response.body) { const data = await response.json().catch(() => null); throw new Error(data?.error || 'Generation failed.'); } const reader = response.body.getReader(); const decoder = new TextDecoder(); let text = ''; while (true) { const { done, value } = await reader.read(); if (done) break; text += decoder.decode(value, { stream: true }); setAnswer(text); } } catch (cause) { setError(cause instanceof Error ? cause.message : 'RAG playground failed.'); } finally { setLoading(false); } };
 return <div className="mt-4 rounded-xl border border-[var(--accent-cyan)]/25 bg-[var(--bg-primary)]/40 p-5"><p className="text-sm text-[var(--text-secondary)]">Uses the real Knowledge API and Groq route. Add a public sample document in Knowledge Base first.</p><div className="mt-4 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 flex-1 rounded-lg border border-[var(--border-color)] bg-[var(--bg-primary)] p-2.5 text-sm" /><button onClick={run} disabled={loading} className="inline-flex items-center gap-1 rounded-lg bg-[var(--accent-cyan)] px-3 text-sm font-bold text-slate-950 disabled:opacity-50">{loading ? <LoaderCircle size={15} className="animate-spin" /> : <Search size={15} />} Run</button></div>{error && <p className="mt-3 text-sm text-rose-400">{error}</p>}<div className="mt-5 grid gap-3 text-sm"><Stage title="1. User Question">{query}</Stage><Stage title="2. Question Embedding">384 dimensions generated server-side; vector values are intentionally hidden.</Stage><Stage title="3. Retrieval">{results.length ? results.map((result) => <p key={`${result.documentTitle}-${result.chunkIndex}`}>{result.documentTitle} · chunk {result.chunkIndex + 1} · {Math.round(result.score * 100)}%</p>) : 'Run the search to see retrieved chunks.'}</Stage><Stage title="4. Context Builder"><pre className="max-h-48 overflow-auto whitespace-pre-wrap font-sans text-xs">{context ? context.slice(0, 4000) : 'Safe context appears here after retrieval.'}</pre></Stage><Stage title="5. Generation">{answer || 'The grounded Groq answer streams here.'}</Stage></div></div>; }
function Stage({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-lg border border-[var(--border-color)] p-3"><h3 className="font-mono text-xs text-[var(--accent-cyan)]">{title}</h3><div className="mt-2 text-[var(--text-secondary)]">{children}</div></section>; }
