export type LinkPlatform = 'linkedin'|'github'|'gitlab'|'twitter'|'instagram'|'website'|'portfolio';
export interface ExtractedLink { platform: LinkPlatform; url: string; }
export interface ExtractedEntities { personNames: string[]; emails: string[]; phoneNumbers: string[]; urls: string[]; linkedinUrls: string[]; githubUrls: string[]; portfolioUrls: string[]; socialProfileUrls: string[]; organizations: string[]; roles: string[]; technologies: string[]; links: ExtractedLink[]; }
const urlPattern = /(?:(?:https?:\/\/)?(?:www\.)?[a-z0-9.-]+\.[a-z]{2,}(?:\/[^\s|,;)]*)?)/gi;
const emailPattern = /[\w.+-]+@[\w.-]+\.[a-z]{2,}/gi; const phonePattern = /\+?\d[\d\s()-]{7,}\d/g;
function normalizeUrl(value: string) { const exact = value.replace(/[.,;]+$/, ''); const comparable = /^https?:\/\//i.test(exact) ? exact : `https://${exact}`; try { const parsed = new URL(comparable); return { exact, domain: parsed.hostname.toLowerCase() }; } catch { return null; } }
function platform(domain: string): LinkPlatform { if (domain.includes('linkedin.com')) return 'linkedin'; if (domain.includes('github.com')) return 'github'; if (domain.includes('gitlab.com')) return 'gitlab'; if (domain.includes('twitter.com') || domain === 'x.com' || domain.endsWith('.x.com')) return 'twitter'; if (domain.includes('instagram.com')) return 'instagram'; if (domain.includes('portfolio')) return 'portfolio'; return 'website'; }
function titleCase(value: string) { return value.toLowerCase().replace(/\b[a-z]/g, (letter) => letter.toUpperCase()); }
export function extractEntities(content: string): ExtractedEntities { const urls = [...new Set((content.match(urlPattern) ?? []).filter((value) => !emailPattern.test(value)))]; const links = urls.map(normalizeUrl).filter((value): value is NonNullable<typeof value> => Boolean(value)).map((value) => ({ platform: platform(value.domain), url: value.exact })); const lines = content.split(/\n+/); const labelledNames = lines.flatMap((line) => [...line.matchAll(/(?:^|\b)(?:name|full name)\s*:\s*([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,2})/gi)].map((match) => match[1])); const standaloneNames = lines.filter((line) => /^[A-Z]{2,}(?:\s+[A-Z]{2,}){1,2}$/.test(line.trim()) && !/\b(?:SUMMARY|EDUCATION|EXPERIENCE|SKILLS|PROJECT|CONTACT)\b/.test(line)).map((line) => titleCase(line.trim())); const names = [...labelledNames, ...standaloneNames]; const roles = lines.flatMap((line) => [...line.matchAll(/(?:role|position|title)\s*:\s*([^\n]+)/gi)].map((match) => match[1].trim())).concat(lines.filter((line) => /\b(?:owner|founder|creator)\b/i.test(line) && line.length < 120).map((line) => line.trim())); const organizations = lines.flatMap((line) => [...line.matchAll(/(?:organization|company|university)\s*:\s*([^\n]+)/gi)].map((match) => match[1].trim())); const technologies = [...new Set((content.match(/\b(?:react(?:\.js)?|node(?:\.js)?|typescript|javascript|mongodb|express(?:\.js)?|php|html|css|bootstrap)\b/gi) ?? []).map((value) => value.toLowerCase()))]; const emails = [...new Set(content.match(emailPattern) ?? [])]; return { personNames: [...new Set(names)], emails, phoneNumbers: [...new Set(content.match(phonePattern) ?? [])], urls: links.map((link) => link.url), linkedinUrls: links.filter((link) => link.platform === 'linkedin').map((link) => link.url), githubUrls: links.filter((link) => link.platform === 'github').map((link) => link.url), portfolioUrls: links.filter((link) => link.platform === 'portfolio').map((link) => link.url), socialProfileUrls: links.filter((link) => ['linkedin','github','gitlab','twitter','instagram'].includes(link.platform)).map((link) => link.url), organizations: [...new Set(organizations)], roles: [...new Set(roles)], technologies, links }; }
