export type ProfileIntent = 'linkedin_profile'|'github_profile'|'portfolio_url'|'email'|'phone'|'owner'|'role'|'skills'|'education'|'project'|'general_knowledge';
export interface QueryIntent { intent: ProfileIntent; personName?: string; platform?: 'linkedin'|'github'|'portfolio'; normalizedQuery: string; aliases: string[]; }
const FILLERS = new Set(['ni','no','ne','ki','ka','ke','su','shu','ch','che','hai','he','batao','aap','aapo','what','is','the','of','ka']);
function normalize(query: string) { return query.toLowerCase().replace(/(?:'s|’s)\b/g,'').replace(/linkdin/g,'linkedin').replace(/git hub/g,'github').replace(/linked in/g,'linkedin').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim(); }
export function parseQueryIntent(query: string): QueryIntent {
 const normalizedQuery = normalize(query); const terms = normalizedQuery.split(' ').filter(Boolean); const meaningful = terms.filter((term) => !FILLERS.has(term));
 let intent: ProfileIntent = 'general_knowledge'; let platform: QueryIntent['platform'];
 if (/linkedin|professional profile/.test(normalizedQuery)) { intent='linkedin_profile'; platform='linkedin'; } else if (/github|repository profile/.test(normalizedQuery)) { intent='github_profile'; platform='github'; } else if (/portfolio/.test(normalizedQuery)) { intent='portfolio_url'; platform='portfolio'; } else if (/email|mail/.test(normalizedQuery)) intent='email'; else if (/phone|mobile|contact number/.test(normalizedQuery)) intent='phone'; else if (/owner|founder|creator|built by|owns/.test(normalizedQuery)) intent='owner'; else if (/role|position|designation/.test(normalizedQuery)) intent='role'; else if (/skills|technology|tech stack/.test(normalizedQuery)) intent='skills'; else if (/education|university|degree/.test(normalizedQuery)) intent='education'; else if (/project|work/.test(normalizedQuery)) intent='project';
 const anchor = meaningful.findIndex((term) => ['linkedin','github','portfolio','email','phone','owner','founder','role','skills','education','project'].includes(term)); const nameParts = (anchor >= 2 ? meaningful.slice(Math.max(0,anchor-2),anchor) : meaningful.slice(0,2)).filter((term) => term.length > 1 && !['professional','profile','repository'].includes(term)); const personName = nameParts.length >= 2 ? nameParts.slice(0,3).map((term) => `${term[0].toUpperCase()}${term.slice(1)}`).join(' ') : undefined; const aliases = personName ? [personName, personName.split(' ').reverse().join(' ')] : [];
 return { intent, personName, platform, normalizedQuery, aliases: [...new Set(aliases)] };
}
